controller_list:
  - name: /mars_joint_controller
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints: [base_link_to_base_cylinder, base_cylinder_to_link2, link_2_to_link_3, link_3_to_link_4, link_4_to_gripper_base]
      
  #- name: gazebo_MARS_prototype/gripper_controller
    #action_ns: follow_joint_trajectory
    #type: FollowJointTrajectory
    #default: true
    #joints: [gripper_base_to_finger_base1,finger_base1_to_finger_top1,gripper_base_to_finger_base2,finger_base2_to_finger_top2,gripper_base_to_finger_base3,finger_base3_to_finger_top3]