# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  base_cylinder_to_link2:
    has_velocity_limits: true
    max_velocity: 0.2094
    has_acceleration_limits: false
    max_acceleration: 0
  base_link_to_base_cylinder:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  link_2_to_link_3:
    has_velocity_limits: true
    max_velocity: 5.2359
    has_acceleration_limits: false
    max_acceleration: 0
  link_3_to_link_4:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0
  link_4_to_gripper_base:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: false
    max_acceleration: 0